#!/usr/bin/env node
/**
 * Hivory Design System — icon subset builder.
 *
 * Tabler ships 5,193 glyphs as a 462KB webfont plus 211KB of CSS, loaded from a
 * third-party CDN. The system uses a few dozen of them. Every consumer was
 * paying ~673KB and a jsdelivr round trip on every cold load to render less
 * than one percent of a font.
 *
 * This subsets the font to exactly the glyphs in icons.txt and emits a
 * self-hosted stylesheet. Adding a glyph is a deliberate act — a line in
 * icons.txt and a rebuild — which is how the system governs its icon set
 * anyway: a new glyph is a design decision, recorded, not an invention at the
 * call site.
 *
 * Usage: node scripts/build-icons.mjs   (needs .tmp/tabler.css + .tmp/tabler.woff2)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';

const SRC_CSS = '.tmp/tabler.css';
const SRC_FONT = '.tmp/tabler.woff2';
const MANIFEST = 'icons.txt';

if (!existsSync(SRC_CSS) || !existsSync(SRC_FONT)) {
  console.error('Missing .tmp/tabler.css or .tmp/tabler.woff2 — see the header.');
  process.exit(1);
}

const version = (/woff2\?v([0-9.]+)/.exec(readFileSync(SRC_CSS, 'utf8')) || [, 'unknown'])[1];
const css = readFileSync(SRC_CSS, 'utf8');

// name -> codepoint, from Tabler's own rules
const codepoints = new Map();
for (const m of css.matchAll(/\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-fA-F]+)"/g)) {
  codepoints.set(m[1], m[2]);
}

const wanted = readFileSync(MANIFEST, 'utf8')
  .split('\n')
  .map((l) => l.replace(/#.*$/, '').trim())
  .filter(Boolean)
  .map((n) => n.replace(/^ti-/, ''));

const missing = wanted.filter((n) => !codepoints.has(n));
if (missing.length) {
  console.error(`Not in Tabler ${version}: ${missing.join(', ')}`);
  process.exit(1);
}

const unicodes = wanted.map((n) => `U+${codepoints.get(n)}`).join(',');

execFileSync(
  'python3',
  [
    '-m', 'fontTools.subset', SRC_FONT,
    `--unicodes=${unicodes}`,
    '--flavor=woff2',
    '--output-file=assets/fonts/tabler-subset.woff2',
    '--no-hinting', '--desubroutinize', '--drop-tables+=DSIG',
  ],
  { stdio: 'inherit' },
);

const rules = wanted
  .map((n) => `.ti-${n}:before { content: "\\${codepoints.get(n)}"; }`)
  .join('\n');

writeFileSync(
  'icons.css',
  `/* GENERATED by scripts/build-icons.mjs — do not edit.\n` +
    `   Tabler ${version}, subset to the ${wanted.length} glyphs in icons.txt.\n` +
    `   Self-hosted: no third-party request, and none of the 5,193 glyphs the\n` +
    `   system does not use. Add a glyph in icons.txt and rebuild. */\n\n` +
    `@font-face {\n` +
    `  font-family: "tabler-icons";\n` +
    `  font-style: normal;\n` +
    `  font-weight: 400;\n` +
    `  font-display: block;\n` +
    `  src: url("./assets/fonts/tabler-subset.woff2") format("woff2");\n` +
    `}\n\n` +
    `.ti {\n` +
    `  font-family: "tabler-icons" !important;\n` +
    `  speak: never;\n` +
    `  font-style: normal;\n` +
    `  font-weight: 400;\n` +
    `  font-variant: normal;\n` +
    `  text-transform: none;\n` +
    `  line-height: 1;\n` +
    `  -webkit-font-smoothing: antialiased;\n` +
    `  -moz-osx-font-smoothing: grayscale;\n` +
    `}\n\n` +
    rules +
    '\n',
);

const kb = (n) => `${(n / 1024).toFixed(1)}KB`;
console.log(
  `icons: ${wanted.length} glyphs · font ${kb(readFileSync('assets/fonts/tabler-subset.woff2').length)} ` +
    `(was ${kb(readFileSync(SRC_FONT).length)}) · css ${kb(readFileSync('icons.css').length)} (was ${kb(css.length)})`,
);
